spring:
  application:
    name: platform-test
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC
    default-property-inclusion: non_null

  web:
    format:
      date-time: "yyyy-MM-dd'T'HH:mm:ss"

  # Web Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: iso

  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
        base-path: /actuator
    endpoint:
      health:
        show-details: always
    info:
      env:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Logging Configuration
logging:
  level:
    com.inditex.platform: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/platform-test.log

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
  show-actuator: true
  default-flat-param-object: true
  writer-with-order-by-keys: true

# Application Info
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Technical challenge for Inditex Platform team - Price Query Service
    encoding: UTF-8
    java:
      version: ${java.version}

# Custom Application Properties
app:
  price:
    cache:
      ttl: 300 # seconds
      max-size: 1000
  api:
    version: v1
    base-path: /api/${app.api.version}
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always

logging:
  level:
    com.inditex.platform: DEBUG
    org.springframework.test: INFO
    org.testcontainers: INFO

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

logging:
  level:
    com.inditex.platform: DEBUG

---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: false

  jpa:
    show-sql: false

logging:
  level:
    com.pruebaItx: WARN
    org.springframework: WARN
    org.hibernate: WARN